- platform: statistics
  name: temperature_stats_12h_mean_chambre_arnaud
  entity_id: sensor.temperature_chambre_arnaud
  state_characteristic: mean
  max_age:
    hours: 12

- platform: statistics
  name: temperature_stats_12h_variance_chambre_arnaud
  entity_id: sensor.temperature_chambre_arnaud
  state_characteristic: variance
  max_age:
    hours: 12
